name: silviaduarte
favicon: null
layout_spectrum: 0
typography_spectrum: 0.79832
title: sloduarte
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f1f1'
    - '#000000'
    - '#acb8aa'
    - '#8c907f'
    - '#a46b4e'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.12685471819713712
  rhythmicContrast: 0.06822802382521331
purpose: []
