name: silviaduarte
favicon: null
layout_spectrum: 0.39060911000706255
typography_spectrum: 0.44868701323866844
title: sloduarte
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.892463855445385
  lightness: 0.10610603331588209
  saturation: 0.12685471819713712
  rhythmicContrast: 0.06822802382521331
purpose: []
